# Generated by Django 5.2.4 on 2025-07-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('mobile_no', models.CharField(max_length=15)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
